=== pdelam01/Practicas-Modelado-Semantico-Web/Practica4_XMLSchema/ej01_DTD.dtd
<!ELEMENT personas(persona*)>
<!ELEMENT persona(nombre, apellido, telefono,direccion,profesion*,img)>

<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT direccion ((calle,numero)|(longitud,latitud))>
<!ELEMENT profesion (#PCDATA)>
<!ELEMENT img EMPTY>

<!ELEMENT calle (#PCDATA)>
<!ELEMENT numero (#PCDATA)>
<!ELEMENT latitutd (#PCDATA)>
<!ELEMENT longitud (#PCDATA)>

<!ATTLIST telefono tipo (casa|movil|trabajo) "movil">
<!ATTLIST persona edad CDATA #REQUIRED>
<!ATTLIST personas xmlns CDATA #REQUIRED>
<!ATTLIST img src CDATA #REQUIRED alt CDATA #REQUIRED>

=== pdelam01/Practicas-Modelado-Semantico-Web/Practica4_XMLSchema/ej01_DTD.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE personas SYSTEM "ej01_DTD.dtd">
<personas xmlns="http://torio.unileon.es/~dieigr/personas">
	<persona edad="21">
		<nombre>juan</nombre>
		<apellido>l√≥pez</apellido>
		<telefono tipo="movil">666888999</telefono>
		<direccion>
			<calle>pez</calle>
			<numero>3</numero>
		</direccion>
	<profesion>carpintero</profesion>
    <profesion>dentista</profesion>
    <profesion>piloto F1</profesion>
    <img src="URL1" alt="imagen de pepe"/>
  </persona>
  <persona edad="21">
		<nombre>eva</nombre>
		<apellido>garcia</apellido>
		<telefono tipo="casa">555888999</telefono>		
    <direccion>
			<latitud>3.5</latitud>
			<longitud>42.8</longitud>
		</direccion>
    <img src="URL2" alt="imagen de eva"/>
  </persona>
</personas>
