=== pdelam01/Practicas-Modelado-Semantico-Web/Practica4_XMLSchema/XMLSchema_Vehiculos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" 
           xmlns:target="http://unileon.es/vehiculos" 
           targetNamespace="http://unileon.es/vehiculos" elementFormDefault="qualified">
                      
<xs:simpleType name="medidaMotor">
  <xs:restriction base="xs:integer">
    <xs:minInclusive value="0"/>
    <xs:maxInclusive value="1000"/>
  </xs:restriction>
</xs:simpleType>

  <xs:element name="vehiculos">
    <xs:complexType>
			<xs:sequence>
				<xs:element name="vehiculo" maxOccurs="unbounded">
				  <xs:complexType>
						<xs:sequence>
							<xs:element name="color" type="xs:string"/>
							<xs:element name="marca" type="xs:string"/>
							<xs:element name="potencia">
							 <xs:complexType>
                <xs:simpleContent>
                  <xs:extension base="target:medidaMotor">
                    <xs:attribute name="medida">
                      <xs:simpleType>
                        <xs:restriction base="xs:string">
                          <xs:enumeration value="cv"/>
                          <xs:enumeration value="hp"/>
                          <xs:enumeration value="Kw"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:attribute>
                  </xs:extension>
                </xs:simpleContent>
              </xs:complexType>
            </xs:element>
            </xs:sequence>
              <xs:attribute name="tipo">
                <xs:simpleType>
                  <xs:restriction base="xs:string">
                    <xs:enumeration value="coche"/>
                    <xs:enumeration value="camion"/>
                    <xs:enumeration value="moto"/>
                  </xs:restriction>
                </xs:simpleType>
              </xs:attribute>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== pdelam01/Practicas-Modelado-Semantico-Web/Practica4_XMLSchema/Vehiculos.xml
<?xml version="1.0" encoding="UTF-8"?>
<vehiculos xmlns="http://unileon.es/vehiculos"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://unileon.es/vehiculos XMLSchema_Vehiculos.xsd">
  <vehiculo tipo="coche">
    <color>rojo</color>
    <marca>Renault</marca>
    <potencia medida="cv">130</potencia>
  </vehiculo>
  <vehiculo tipo="camion">
    <color>blanco</color>
    <marca>Scania</marca>
    <potencia medida="cv">400</potencia>
  </vehiculo>
</vehiculos>
